# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
use_frameworks!
target 'TwoHrs' do
  # Comment the next line if you don't want to use dynamic frameworks
  
  pod 'Alamofire'
  

  # Pods for TwoHrs

  target 'TwoHrsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TwoHrsUITests' do
    # Pods for testing
  end

end
